### ISSUE TITLE
Bug: undefined preceding link when alias is deifned

### ISSUE THREAD

**Issue by davidfers** [YU000jp/logseq-plugin-short-namespaces#27]
The new v1.7.0 is causing this bug for links with alias defined

<img src="https://github.com/YU000jp/logseq-plugin-short-namespaces/assets/60383773/9da55546-2b85-48e1-93e4-ab99eda625bb" width=40% height=40%/>
<br><br>
<img src="https://github.com/YU000jp/logseq-plugin-short-namespaces/assets/60383773/15bbec62-e4e0-40da-afeb-6b780766ec10" width=40% height=40%/>

**Comment by rowsof** [comment]
Confirming this issue is 100% reproducible on standard [[links]] (links without a parent namespace) that point to a page with an alias. This doesn't appear to occur on [[namespace/links]].

**Comment by YU000jp** [comment]
It is a bug. I plan to fix it as soon as possible.

**Comment by YU000jp** [comment]
I released a new version.

**Comment by mcules** [comment]
The problem still exists for me on v1.7.1
![image](https://github.com/YU000jp/logseq-plugin-short-namespaces/assets/5315463/85b0a242-fe2d-417d-9efb-c7485e8a7f78)

**Comment by mcules** [comment]
Works perfekt now. Thanks a lot 👍
